apiVersion: v1
kind: Service
metadata:
  name: {{ include "search-engine-crawler.fullname" . }}
  labels:
    {{- include "search-engine-crawler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "search-engine-crawler.selectorLabels" . | nindent 4 }}
