name: test :)

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Install yc
      run: 'curl -s https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash'

    - name: check
      run: |
        cat ~/.bashrc
        source ~/.bashrc
        yc --help

